INC = -Isrc/comm/base/ -Isrc/comm/epoller/ -Isrc/comm/fsm/ -Isrc/comm/log/ -Isrc/comm/net_handler\
	  -Isrc/app/action_info/ -Isrc/app/appactor/ -Isrc/app/appfsm/ -Isrc/app/socketactor/ -Isrc/app/socketfsm/ -Isrc/app/frame
